# Generated by Django 3.1.2 on 2020-10-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20201028_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_pic', models.ImageField(upload_to='static/images/')),
            ],
        ),
    ]
