# Generated by Django 3.1.2 on 2020-10-28 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_biopic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biopic',
            old_name='bio_pic',
            new_name='image',
        ),
    ]
