# Generated by Django 3.1.2 on 2020-10-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_backgroundimage_certifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='current_job',
            field=models.BooleanField(default=False),
        ),
    ]
