# Generated by Django 3.1.2 on 2020-10-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20201029_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='certifications',
            name='cert_badge',
            field=models.TextField(default=''),
        ),
    ]
