# Generated by Django 3.1.2 on 2020-10-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_certifications_cert_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.URLField(),
        ),
    ]
